name: Not a real CI/CD Pipeline

on:
  push:
    branches:
      - "*"

jobs:
  call-pipeline-manager:
    uses: ${{ github.repository_owner }}/.github/.github/workflows/cp-pipeline-ci.yml@main

    
