name: Pipeline CI Orchestrator

on:
  push:
    branches:
      - "*"

jobs:
  pipeline-ci-orchestrator:
    name: Execute Pipeline CI
    uses: bcit-ltc/.github/.github/workflows/cp-pipeline-ci-reusable.yml@main
    secrets:
      HELM_REPO_PAT: ${{ secrets.HELM_REPO_PAT }}
      DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}