name: Pipeline Manager

on:
  push:
    branches:
      - "*"

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  packages: write # Required for pushing images  

jobs:
  pipeline-manager:
    name: Pipeline Manager
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # - name: Print all ENVS
      #   run: printenv
      - name: Run Dagger for pipeline-manager development testing
        uses: dagger/dagger-for-github@8.0.0
        env:
          # setting tokens here so that it can be referenced below without exposing in dagger cloud logs
          # should be referenced as env://GITHUB_TOKEN in the Dagger module
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HELM_REPO_PAT: ${{ secrets.HELM_REPO_PAT }}
        with:
          # module: github.com/BCIT-LTC/daggerverse/semantic-release
          # call: semanticrelease --username ${{ github.actor }} --github_token env://GITHUB_TOKEN --source ./ 
          module: github.com/BCIT-LTC/daggerverse/pipeline-manager@33-integrate-helm-oci-chart-releaser-into-pipeline-manager
          call: >-
            run 
            --source=. 
            --username=${{ github.actor }} 
            --github_token=env://GITHUB_TOKEN  
            --branch=${{ github.ref_name }} 
            --commit_hash=$(echo $GITHUB_SHA | cut -c1-7) 
            --registry_path=ghcr.io/$(echo "${{ github.repository }}") 
            --repository_url=$(echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY)
            --helm_repo_pat=env://HELM_REPO_PAT
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "latest"
          